project:
  name: orthotech_dev_duplicate
  cpp_standard: 17

dependencies:
  common:
    packages:
      - cmake

  linux:
    packages:
      - build-essential
      - g++
      - make
      - libeigen3-dev
      - libboost-all-dev
    source:
      - ur_rtde

  windows:
    source:
      - ur_rtde
    vcpkg:
      - eigen3
      - boost

outputs:
  linux: linux-requirements.json
  windows: windows-requirements.json
