name: Linux Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build